apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask_app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 5000  # Port on which your Flask app is running inside the container
  type: LoadBalancer
